version: "3.5"

services:
  node:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/node_modules
    ports:
      - "4200:4200"
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
